

version: 1.0.{build}

build_script:

- ps: Invoke-WebRequest -Uri https://github.com/ovh/venom/releases/download/v1.1.0/venom.windows-amd64 -OutFile venom.exe
- cmd: choco install podman-cli
- cmd: podman -v

test_script:
- cmd: venom run -v test1.yml
